apiVersion: v1
kind: Service
metadata:
  name: orion-service
  labels:
    name: orionservice-nodeport-svc
spec:
  type: NodePort
  ports:
    - port: 1026
      nodePort: 30190
      name: http
    - port: 443
      nodePort: 31445
      name: https
  selector:
    name: broker
